kind: Service
apiVersion: v1
metadata:
  name: php-example-1-service
  namespace: giaplv-demo
spec:
  selector:
    app: php-example-1
  type: NodePort
  ports:
  - nodePort: 30324
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-example-1
  namespace: giaplv-demo
  labels:
    app: php-example-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-example-1
  template:
    metadata:
      labels:
        app: php-example-1
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - env: 
        - name: CID
          value: vn
        image: giaple/demogo:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 80
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: te-k8s-php-example-1
        ports:
        - containerPort: 80

