kind: Service
apiVersion: v1
metadata:
  name: php-example-2-service
  namespace: giaplv-demo
spec:
  selector:
    app: php-example-2
  type: NodePort
  ports:
  - nodePort: 30326
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-example-2
  namespace: giaplv-demo
  labels:
    app: php-example-2
spec:
   replicas: 1
   selector:
    matchLabels:
      app: php-example-2
   template:
    metadata:
     labels:
         app: php-example-2
   spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        valueFrom:
          - configMapRef:
            name: env-variables
        env: 
         - name: CID
           value: vn
         - name: HELLO_WORLD
           value: $(HELLO)_$(WORLD)
        image: giaple/demogo:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: $port
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: te-k8s-php-example-2
        ports:
        - containerPort: $port

